Adding bsv enum generation from rdl enums
oxidecomputer/cobalt pull request #47
Opened 2022-12-19 16:45 UTC by nathanaelhuffman

This added RDL-specified enums to generate enums in the BSV package.  This is the first step in a series of steps to getting this end-end supported, but this was complete and useful now on the bsv side so I'm breaking this out separately.

Future work includes work on the rust generation side to generate Rust Enums also.  This was more invasive to our current Rust generation workflow and so will be done separately.

Right now, this fixes the html generation and the bsv package generation, leaving the json/rust stuff for future work.

Additionally, BSV has no way of disambiguating multiple enum members with the same name in the same package so we throw errors if you have conflicting enum names since we're generating one big package here.

2022-12-20 16:41 UTC, nathanaelhuffman commented
This is picked up in hubris: https://github.com/oxidecomputer/hubris/pull/1036, will let that review finish since it could impact json output, but is backwards compatible and once that settles I'll merge this.

2022-12-20 18:02 UTC, arjenroodselaar requested changes
See the inline comment. Otherwise this looks great, looking forward to using this!

2022-12-20 18:02 UTC, arjenroodselaar commented on tools/site_cobble/rdl_pkg/models.py
> +                        raise DuplicateEnumNameError("Enum member '{}' on register '{}' has previously used enum name".format(name, self.name))
Very actionable error message, this is great.

2022-12-20 19:10 UTC, nathanaelhuffman commented on RDL_EXAMPLES.md
> +    IDLE = 0,
I can clean this up in some places like this. BSV has... opinions about the case of things in some places, so some munging is required in some cases, but the values in an ENUM aren't one of those.

2022-12-20 19:49 UTC, arjenroodselaar approved these changes
shipit!

2022-12-20 22:45 UTC, Aaron-Hartwig approved these changes
Thanks for the work here, this is really great!

2022-12-20 23:15 UTC, merged

2023-01-04 08:39 UTC, arjenroodselaar commented
> Additionally, BSV has no way of disambiguating multiple enum members with the same name in the same package so we throw errors if you have conflicting enum names since we're generating one big package here.
We should reconsider this because I realized last week there is a way to disambiguate between enum members with the same name. The syntax is `<type>'(<member name)`. See https://github.com/oxidecomputer/cobalt/blob/56aeb2bac70332a7c92ca8e5d18977ae14f1e1fe/hdl/LogicSampler.bsv#L783

The `Invalid` and `Ok` members exist several times in that package.